Add tutorial for ROS 2 galactic [12701]
eProsima/Fast-DDS-monitor pull request #126
Opened 2021-10-15 11:54 UTC by jparisu

Signed-off-by: jparisu <javierparis@eprosima.com>

2021-10-18 07:59 UTC, juanlofer-eprosima requested changes

2021-10-18 07:59 UTC, juanlofer-eprosima commented on docs/rst/ros/galactic/galactic.rst
> +- To activate the report of statistic data, Fast DDS requires to use an environmental variable setting up those
```suggestion
- In order to activate the publication of statistical data, Fast DDS requires an environment variable specifying those
```

2021-10-18 07:59 UTC, juanlofer-eprosima commented on docs/rst/ros/galactic/galactic.rst
> +    statistic kinds that are going to be reported.
```suggestion
    kinds of statistical data to be reported.
```

2021-10-18 07:59 UTC, juanlofer-eprosima commented on docs/rst/ros/galactic/galactic.rst
> +    export FASTDDS_STATISTICS="HISTORY_LATENCY_TOPIC;SUBSCRIPTION_THROUGHPUT_TOPIC;PHYSICAL_DATA_TOPIC" # add as many statistics topic as wanted
```suggestion
    export FASTDDS_STATISTICS="HISTORY_LATENCY_TOPIC;SUBSCRIPTION_THROUGHPUT_TOPIC;PHYSICAL_DATA_TOPIC" # add as many statistics topics as wanted
```

2021-10-18 07:59 UTC, juanlofer-eprosima commented on docs/rst/ros/galactic/galactic.rst
> +    export FASTDDS_STATISTICS="HISTORY_LATENCY_TOPIC;SUBSCRIPTION_THROUGHPUT_TOPIC;PHYSICAL_DATA_TOPIC" # add as many statistics topic as wanted
```suggestion
    export FASTDDS_STATISTICS="HISTORY_LATENCY_TOPIC;SUBSCRIPTION_THROUGHPUT_TOPIC;PHYSICAL_DATA_TOPIC" # add as many statistics topics as wanted
```

2021-10-18 07:59 UTC, juanlofer-eprosima commented on docs/rst/ros/galactic/galactic.rst
> +Now you must see in the Fast DDS Monitor two new Participants.
```suggestion
Now you should see in the DDS panel two new Participants.
```

2021-10-18 07:59 UTC, juanlofer-eprosima commented on docs/rst/ros/galactic/galactic.rst
> +Participants in ROS 2 are called :code:`\ `.
```suggestion
Participants in ROS 2 are named :code:`\ ` by default.
```

2021-10-18 07:59 UTC, juanlofer-eprosima commented on docs/rst/ros/galactic/galactic.rst
> +In order to differentiate them you could :ref:`change_alias`.
```suggestion
In order to differentiate them one could :ref:`change_alias`.
```

2021-10-18 07:59 UTC, juanlofer-eprosima commented on docs/rst/ros/galactic/galactic.rst
> +The :code:`talker` would be the one with one writer, and the :code:`listener` with a reader.
```suggestion
The :code:`talker` would be the one with one writer, and the :code:`listener` the one with a reader.
```

2021-10-18 07:59 UTC, juanlofer-eprosima commented on docs/rst/ros/galactic/galactic.rst
> +In order to see the information about the host and the physical context where every node is running, go to
```suggestion
In order to see the information of the host and the physical context where every node is running, go to
```

2021-10-18 07:59 UTC, juanlofer-eprosima commented on docs/rst/ros/galactic/galactic.rst
> +There are shown the host, user and process of each node.
```suggestion
There, the host, user and process of each node are displayed.
```

2021-10-18 07:59 UTC, juanlofer-eprosima commented on docs/rst/ros/galactic/galactic.rst
> +To show statistical data about the communication between the :code:`talker` and the :code:`listener`.
```suggestion
To show statistical data about the communication between the :code:`talker` and the :code:`listener`,
```

2021-10-18 07:59 UTC, juanlofer-eprosima commented on docs/rst/ros/galactic/galactic.rst
> +Follow the steps to :ref:`tutorial_create_dynamic_series` and see this statistical data graphically in a real
```suggestion
follow the steps to :ref:`tutorial_create_dynamic_series` and plot this statistical data in a real
```

2021-10-18 07:59 UTC, juanlofer-eprosima commented on docs/rst/ros/galactic/galactic.rst
> +Fast DDS Monitor filters by default the metatraffic topics and the endpoints related to them so the user
```suggestion
Fast DDS Monitor filters by default the topics used for sharing metatraffic and the endpoints related to them so the user
```

2021-10-18 07:59 UTC, juanlofer-eprosima commented on docs/rst/ros/galactic/galactic.rst
> +can inspection its network easily.
```suggestion
can inspect its network easily.
```

2021-10-18 07:59 UTC, juanlofer-eprosima commented on docs/rst/ros/galactic/galactic.rst
> +These topics are the ones that ROS 2 uses for discovery and configuration, such as `ros_discovery_info`.
```suggestion
These topics are the ones that ROS 2 uses for discovery and configuration purposes, such as `ros_discovery_info`,
```

2021-10-18 07:59 UTC, juanlofer-eprosima commented on docs/rst/ros/galactic/galactic.rst
> +And those used by Fast DDS to report statistical data.
```suggestion
 as well as those used by Fast DDS to report statistical data.
```

2021-10-18 07:59 UTC, juanlofer-eprosima commented on docs/rst/ros/galactic/galactic.rst
> +In order to see these topics in the monitor, click .
click reference is missing

2021-10-18 07:59 UTC, juanlofer-eprosima commented on docs/rst/ros/galactic/galactic.rst
> +Now, these topics will be shown in the logical panel, and the Readers and Writers associated to them under their
```suggestion
Now, these topics are shown in the logical panel, and also the Readers and Writers associated to them under their
```

2021-10-18 07:59 UTC, juanlofer-eprosima commented on docs/rst/ros/galactic/galactic.rst
> +There is a `video tutorial <https://www.youtube.com/watch?v=OYibnUnMIlc>`_ briefly showing the tutorial
```suggestion
There is a `video tutorial <https://www.youtube.com/watch?v=OYibnUnMIlc>`_ going through the steps
```

2021-10-18 07:59 UTC, juanlofer-eprosima commented on docs/rst/ros/galactic/galactic.rst
> +There is a `video tutorial <https://www.youtube.com/watch?v=OYibnUnMIlc>`_ briefly showing the tutorial
Video link to be modified after reuploading new version

2021-10-18 07:59 UTC, juanlofer-eprosima commented on docs/rst/ros/galactic/galactic.rst
> +that has been explained in this section.
```suggestion
described in this section.
```

2021-10-18 07:59 UTC, juanlofer-eprosima commented on docs/rst/ros/ros.rst
> +Fast DDS Monitor is a very useful tool to monitor and study a ROS 2 network.
```suggestion
Fast DDS Monitor is a useful tool for monitoring and studying a ROS 2 network.
```

2021-10-18 07:59 UTC, juanlofer-eprosima commented on docs/rst/ros/ros.rst
> +used to communicate each other.
```suggestion
to communicate with each another.
```

2021-10-18 07:59 UTC, juanlofer-eprosima commented on docs/rst/ros/ros.rst
> +are running, as its endpoints, the topics that each one is using, and even the network interfaces that are being
```suggestion
are running, as its endpoints, the topics that each one is using, and even the network interfaces they are using
```

2021-10-18 07:59 UTC, juanlofer-eprosima commented on docs/rst/ros/ros.rst
> +Additionally, you could receive statistics data from every endpoint in the network.
```suggestion
Additionally, one could receive statistical data from every endpoint in the network.
```

2021-10-18 07:59 UTC, juanlofer-eprosima commented on docs/rst/ros/ros.rst
> +Just be sure to use Fast DDS as your ROS 2 middleware in order to receive statistic data and monitor your network.
```suggestion
Make sure you are using Fast DDS as your ROS 2 middleware in order to receive statistical data and monitor your network.
```

2021-10-18 07:59 UTC, juanlofer-eprosima commented on docs/rst/ros/ros.rst
> +In the following sections are described how to use Fast DDS with Statistics active in different ROS2 versions.
```suggestion
In the following sections, instructions for using Fast DDS with Statistics in different ROS2 versions are provided, as well as a brief tutorial demonstrating the integration of Fast DDS Monitor with ROS2 in a simple scenario.
```

2021-10-18 12:14 UTC, jparisu commented on docs/rst/ros/galactic/galactic.rst
> +Initiate Fast DDS Monitor by the executable created by the installation process.
:+1:

2021-10-18 12:15 UTC, jparisu commented on docs/rst/ros/galactic/galactic.rst
> +Once into the Fast DDS Monitor window, start a monitor in domain :code:`0` (default domain).
:+1:

2021-10-18 12:16 UTC, jparisu commented on docs/rst/ros/galactic/galactic.rst
> +- To activate the report of statistic data, Fast DDS requires to use an environmental variable setting up those
:+1:

2021-10-18 12:17 UTC, jparisu commented on docs/rst/ros/galactic/galactic.rst
> +    statistic kinds that are going to be reported.
:+1:

2021-10-18 12:17 UTC, jparisu commented on docs/rst/ros/galactic/galactic.rst
> +    export FASTDDS_STATISTICS="HISTORY_LATENCY_TOPIC;SUBSCRIPTION_THROUGHPUT_TOPIC;PHYSICAL_DATA_TOPIC" # add as many statistics topic as wanted
:+1:

2021-10-18 12:21 UTC, jparisu commented on docs/rst/ros/galactic/galactic.rst
> +In order to differentiate them you could :ref:`change_alias`.
:+1:

2021-10-18 12:22 UTC, jparisu commented on docs/rst/ros/galactic/galactic.rst
> +In order to see the information about the host and the physical context where every node is running, go to
:+1:

2021-10-18 12:23 UTC, jparisu commented on docs/rst/ros/galactic/galactic.rst
> +To show statistical data about the communication between the :code:`talker` and the :code:`listener`.
:+1:

2021-10-18 12:24 UTC, jparisu commented on docs/rst/ros/galactic/galactic.rst
> +Follow the steps to :ref:`tutorial_create_dynamic_series` and see this statistical data graphically in a real
:+1:

2021-10-18 12:25 UTC, jparisu commented on docs/rst/ros/galactic/galactic.rst
> +Fast DDS Monitor filters by default the metatraffic topics and the endpoints related to them so the user
:+1:

2021-10-18 12:27 UTC, jparisu commented on docs/rst/ros/galactic/galactic.rst
> +These topics are the ones that ROS 2 uses for discovery and configuration, such as `ros_discovery_info`.
:+1:

2021-10-18 12:29 UTC, jparisu commented on docs/rst/ros/galactic/galactic.rst
> +Now, these topics will be shown in the logical panel, and the Readers and Writers associated to them under their
:+1:

2021-10-18 12:34 UTC, jparisu commented on docs/rst/ros/galactic/galactic.rst
> +that has been explained in this section.
:+1:

2021-10-18 12:35 UTC, jparisu commented on docs/rst/ros/ros.rst
> +The automatic discovery of entities in a local network allows to easily see the different Participants that
Use capital letter for Participants to keep the documentation format

2021-10-18 12:36 UTC, jparisu commented on docs/rst/ros/ros.rst
> +are running, as its endpoints, the topics that each one is using, and even the network interfaces that are being
:+1:

2021-10-18 12:59 UTC, juanlofer-eprosima commented on docs/rst/ros/ros.rst
> +used to communicate each other.
sorry, I meant "with each other"

2021-10-18 13:03 UTC, juanlofer-eprosima commented on docs/rst/ros/ros.rst
> +Additionally, you could receive statistics data from every endpoint in the network.
impersonal?

2021-10-19 08:41 UTC, juanlofer-eprosima requested changes
Please check the open threads

2021-10-19 14:10 UTC, juanlofer-eprosima commented
LGTM

2021-10-19 14:31 UTC, merged