Release Notes for v1.1.0
eProsima/Fast-DDS-monitor pull request #137
Opened 2021-12-16 08:33 UTC by jparisu

Signed-off-by: jparisu <javierparis@eprosima.com>

2021-12-17 06:42 UTC, rsanchez15 requested changes

2021-12-17 06:42 UTC, rsanchez15 commented on docs/rst/notes/notes.rst
> +* Support cumulative data Dynamic Chart.
```suggestion
* Support cumulative data in Dynamic Charts.
```

2021-12-17 06:42 UTC, rsanchez15 commented on docs/rst/notes/notes.rst
> +* Fix width QML warning.
This is not done yet but I'm on it. 

```suggestion
* Fix width QML warning.
* Fix mu(micro) symbol display in Windows
```

2021-12-17 06:57 UTC, jparisu commented on docs/rst/notes/notes.rst
> +* Support cumulative data Dynamic Chart.
:+1:

2021-12-17 06:57 UTC, jparisu commented on docs/rst/notes/notes.rst
> +* Fix width QML warning.
:+1:

2021-12-17 07:01 UTC, jparisu commented on docs/rst/notes/notes.rst
> +
:+1:

2021-12-17 14:35 UTC, rsanchez15 requested changes

2021-12-17 14:35 UTC, rsanchez15 commented on docs/rst/notes/notes.rst
> +* Blank text when open change alias dialog.
```suggestion
* Blank text when open "*change alias*" dialog.
```

2021-12-21 09:12 UTC, rsanchez15 approved these changes

2021-12-21 09:12 UTC, merged