[21446] Fast DDS Monitor refactor: Fast DDS v3 compatibility
eProsima/Fast-DDS-monitor pull request #227
Opened 2024-08-01 08:41 UTC by Carlosespicur

Add minor changes for Monitor compilation with Fast DDS v3. Fast DDS Statistics Backend migration to Fast DDS v3 (https://github.com/eProsima/Fast-DDS-statistics-backend/pull/239) required.

2024-08-28 11:16 UTC, JesusPoderoso requested changes

2024-08-28 11:16 UTC, JesusPoderoso commented on docs/rst/notes/notes.rst
I think these changes are unnecessary, as long as the product name is displayed in the first column of the table (see [here](https://fast-dds-monitor.readthedocs.io/en/latest/rst/notes/notes.html)).

2024-08-28 11:16 UTC, JesusPoderoso commented on docs/rst/notes/previous_versions/v2.0.0.rst
Same comment as the previous suggestion.
I would keep the `.. _version_v2.0.0:` link but restore the remaining changes

2024-08-28 11:16 UTC, JesusPoderoso commented on docs/rst/ros/galactic/galactic.rst
This document references a previous Fast DDS version (2.9.x) associated with ROS 2 Galactic, so it must not be updated. Please remove the changes

2024-08-29 10:50 UTC, Carlosespicur commented on docs/rst/notes/notes.rst
This changes have been made to avoid a cross reference with the previous versions

2024-08-29 12:15 UTC, JesusPoderoso submitted a review, later dismissed
LGTM with green CI
Lets wait the backend PR to get merged to trigger it

2024-09-11 07:20 UTC, merged