[21458] Add IDL view
eProsima/Fast-DDS-monitor pull request #230
Opened 2024-08-27 06:02 UTC by Carlosespicur

This PR adds a new view to show the IDL representation of a type discovered in logical view and graph.

Needed to be merged before:
https://github.com/eProsima/Fast-DDS-statistics-backend/pull/239
https://github.com/eProsima/Fast-DDS-statistics-backend/pull/245
https://github.com/eProsima/Fast-DDS-monitor/pull/227

2024-09-11 09:52 UTC, JesusPoderoso requested changes
I've generated custom types using Fast DDS Xtypes example to check the idl representation bounds in the tab.
1) Vertically, the scrollbar is so thin when displayed, and mousewheel scrolling is disabled. This should be fixed.
2) Horizontally, the text is not elided when out of bounds.

2024-09-11 09:52 UTC, JesusPoderoso commented on src/Controller.cpp
> +}
EOF

2024-09-11 09:52 UTC, JesusPoderoso commented on src/backend/SyncBackendConnection.cpp
> +}
Remove line break
```suggestion
    }
}
```

2024-09-12 09:02 UTC, Carlosespicur reviewed
Commits reviewed

2024-09-12 10:24 UTC, JesusPoderoso requested changes
A couple of details

2024-09-12 10:24 UTC, JesusPoderoso commented on qml/TabLayout.qml
> +                        ScrollBar.vertical: ScrollBar {
Fix identation in all this included code

2024-09-12 10:24 UTC, JesusPoderoso commented on qml/TabLayout.qml
> +                        anchors.right: parent.right;    anchors.rightMargin: tabLayout.idl_text_margin_/10
Remove right margin
```suggestion
                        anchors.right: parent.right
```

2024-09-12 10:24 UTC, JesusPoderoso commented on qml/TabLayout.qml
> +                        policy: ScrollBar.AlwaysOn
I would make it visible only if necessary:
```suggestion
                        policy: ScrollBar.AlwaysOn
                        visible: idlView.contentHeight > idlView.height
```

2024-09-12 10:42 UTC, JesusPoderoso approved these changes
LGTM with green CI

2024-09-12 13:10 UTC, merged