Refactor historic series
eProsima/Fast-DDS-monitor pull request #92
Opened 2021-07-09 09:17 UTC by jparisu

2021-07-12 05:37 UTC, jparisu commented on src/Engine.cpp
> +                std::chrono::system_clock::now().time_since_epoch()).count()
```suggestion
                time_to.time_since_epoch()).count()
```

2021-07-13 07:51 UTC, rsanchez15 requested changes

2021-07-13 07:51 UTC, rsanchez15 commented on src/statistics/historic/HistoricDataChartBox.cpp
> +    // In case the creation has been succesfull, add all the data
```suggestion
    // In case the creation has been successful, add all the data
```

2021-07-13 07:59 UTC, jparisu commented on include/fastdds_monitor/statistics/StatisticsData.h
> +    //     void axisXMinChanged();
:+1:

2021-07-13 08:00 UTC, jparisu commented on include/fastdds_monitor/statistics/historic/HistoricDataChartBox.h
> + * TODO
:+1:

2021-07-13 10:22 UTC, rsanchez15 approved these changes

2021-07-13 13:26 UTC, rsanchez15 approved these changes
LGTM

2021-07-13 13:26 UTC, merged